<html>
<head>
<title>TestNG:  ValidateX1_DVRDCT_CSGResidential_2</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>ValidateX1_DVRDCT_CSGResidential_2</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>0/1/0</td>
</tr><tr>
<td>Started on:</td><td>Fri Mar 10 21:16:01 IST 2017</td>
</tr>
<tr><td>Total time:</td><td>119 seconds (119356 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED CONFIGURATIONS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='com.comcast.bulkOM.X1_DVRDCT.Cleanup()'><b>Cleanup</b><br>Test class: com.comcast.bulkOM.X1_DVRDCT</td>
<td><div><pre>java.lang.AssertionError: Exception Ocured :null
	at com.comcast.reporting.Report.updateTestLog(Report.java:222)
	at com.comcast.utils.SeleniumReport.reportFailEvent(SeleniumReport.java:114)
	at com.comcast.bom.data.Mongoconnect.BulkomDBCleanup(Mongoconnect.java:590)
	at com.comcast.bulkOM.X1_DVRDCT.Cleanup(X1_DVRDCT.java:186)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace22680556", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace22680556'><pre>java.lang.AssertionError: Exception Ocured :null
	at org.testng.Assert.fail(Assert.java:94)
	at com.comcast.reporting.Report.updateTestLog(Report.java:222)
	at com.comcast.utils.SeleniumReport.reportFailEvent(SeleniumReport.java:114)
	at com.comcast.bom.data.Mongoconnect.BulkomDBCleanup(Mongoconnect.java:590)
	at com.comcast.bulkOM.X1_DVRDCT.Cleanup(X1_DVRDCT.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.TestRunner.afterRun(TestRunner.java:983)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
</pre></div></td>
<td>0</td>
<td>null</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-skipped'>
<tr><td colspan='4' align='center'><b>SKIPPED CONFIGURATIONS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='com.comcast.bulkOM.X1_DVRDCT.tearDown()'><b>tearDown</b><br>Test class: com.comcast.bulkOM.X1_DVRDCT</td>
<td></td>
<td>0</td>
<td>null</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='com.comcast.bulkOM.X1_DVRDCT.ValidateX1_DVRDCT_CSGResidential_2()'><b>ValidateX1_DVRDCT_CSGResidential_2</b><br>Test class: com.comcast.bulkOM.X1_DVRDCT</td>
<td><div><pre>java.lang.AssertionError: Log in is not successful.
	at com.comcast.reporting.Report.updateTestLog(Report.java:222)
	at com.comcast.utils.SeleniumReport.reportFailEvent(SeleniumReport.java:114)
	at com.comcast.bom.pages.BomLoginPage.LoginToBom(BomLoginPage.java:119)
	at com.comcast.bulkOM.X1_DVRDCT.ValidateX1_DVRDCT_CSGResidential_2(X1_DVRDCT.java:104)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace13743824", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace13743824'><pre>java.lang.AssertionError: Log in is not successful.
	at org.testng.Assert.fail(Assert.java:94)
	at com.comcast.reporting.Report.updateTestLog(Report.java:222)
	at com.comcast.utils.SeleniumReport.reportFailEvent(SeleniumReport.java:114)
	at com.comcast.bom.pages.BomLoginPage.LoginToBom(BomLoginPage.java:119)
	at com.comcast.bulkOM.X1_DVRDCT.ValidateX1_DVRDCT_CSGResidential_2(X1_DVRDCT.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
</pre></div></td>
<td>73</td>
<td>com.comcast.bulkOM.X1_DVRDCT@1ec1f0c</td></tr>
</table><p>
</body>
</html>