<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.comcast.bulkOM.X1_DVRDCT" tests="4" time="290.897" ignored="6" failures="4" timestamp="10 Mar 2017 15:48:53 GMT" skipped="0" hostname="LT044891" errors="0">
  <testcase name="ValidateX1_DVRDCT_CSGResidential_2" time="73.388" classname="com.comcast.bulkOM.X1_DVRDCT">
    <failure type="java.lang.AssertionError" message="Log in is not successful.">
      <![CDATA[java.lang.AssertionError: Log in is not successful.
	at org.testng.Assert.fail(Assert.java:94)
	at com.comcast.reporting.Report.updateTestLog(Report.java:222)
	at com.comcast.utils.SeleniumReport.reportFailEvent(SeleniumReport.java:114)
	at com.comcast.bom.pages.BomLoginPage.LoginToBom(BomLoginPage.java:119)
	at com.comcast.bulkOM.X1_DVRDCT.ValidateX1_DVRDCT_CSGResidential_2(X1_DVRDCT.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- ValidateX1_DVRDCT_CSGResidential_2 -->
  <testcase name="Cleanup" time="0.000" classname="com.comcast.bulkOM.X1_DVRDCT">
    <failure type="java.lang.AssertionError" message="Exception Ocured :null">
      <![CDATA[java.lang.AssertionError: Exception Ocured :null
	at org.testng.Assert.fail(Assert.java:94)
	at com.comcast.reporting.Report.updateTestLog(Report.java:222)
	at com.comcast.utils.SeleniumReport.reportFailEvent(SeleniumReport.java:114)
	at com.comcast.bom.data.Mongoconnect.BulkomDBCleanup(Mongoconnect.java:590)
	at com.comcast.bulkOM.X1_DVRDCT.Cleanup(X1_DVRDCT.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.TestRunner.afterRun(TestRunner.java:983)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Cleanup -->
  <testcase name="ValidateX1_DVRDCT_CSGResidential_1" time="122.997" classname="com.comcast.bulkOM.X1_DVRDCT">
    <failure type="java.lang.AssertionError" message="true">
      <![CDATA[java.lang.AssertionError: true
	at org.testng.Assert.fail(Assert.java:94)
	at com.comcast.reporting.Report.updateTestLog(Report.java:222)
	at com.comcast.utils.SeleniumReport.reportFailEvent(SeleniumReport.java:114)
	at com.comcast.bom.data.Mongoconnect.postsubmission_CheckEligibility_X1(Mongoconnect.java:187)
	at com.comcast.bulkOM.X1_DVRDCT.ValidateX1_DVRDCT_CSGResidential_1(X1_DVRDCT.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- ValidateX1_DVRDCT_CSGResidential_1 -->
  <testcase name="ValidateX1_DVRDCT_CSGResidential_3" time="94.512" classname="com.comcast.bulkOM.X1_DVRDCT">
    <failure type="java.lang.AssertionError" message="Upload file is not selected.">
      <![CDATA[java.lang.AssertionError: Upload file is not selected.
	at org.testng.Assert.fail(Assert.java:94)
	at com.comcast.reporting.Report.updateTestLog(Report.java:222)
	at com.comcast.utils.SeleniumReport.reportFailEvent(SeleniumReport.java:114)
	at com.comcast.bom.pages.BomHomePage.HandleAlertForSubmitSwap(BomHomePage.java:197)
	at com.comcast.bom.pages.BomHomePage.enterAccountForX1(BomHomePage.java:180)
	at com.comcast.bulkOM.X1_DVRDCT.ValidateX1_DVRDCT_CSGResidential_3(X1_DVRDCT.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- ValidateX1_DVRDCT_CSGResidential_3 -->
  <testcase name="ValidateX1_DVRDCT_CSGResidential_3" classname="com.comcast.bulkOM.X1_DVRDCT">
    <skipped/>
  </testcase> <!-- ValidateX1_DVRDCT_CSGResidential_3 -->
  <testcase name="ValidateX1_DVRDCT_CSGResidential_3" classname="com.comcast.bulkOM.X1_DVRDCT">
    <skipped/>
  </testcase> <!-- ValidateX1_DVRDCT_CSGResidential_3 -->
  <testcase name="ValidateX1_DVRDCT_CSGResidential_1" classname="com.comcast.bulkOM.X1_DVRDCT">
    <skipped/>
  </testcase> <!-- ValidateX1_DVRDCT_CSGResidential_1 -->
  <testcase name="ValidateX1_DVRDCT_CSGResidential_1" classname="com.comcast.bulkOM.X1_DVRDCT">
    <skipped/>
  </testcase> <!-- ValidateX1_DVRDCT_CSGResidential_1 -->
  <testcase name="ValidateX1_DVRDCT_CSGResidential_2" classname="com.comcast.bulkOM.X1_DVRDCT">
    <skipped/>
  </testcase> <!-- ValidateX1_DVRDCT_CSGResidential_2 -->
  <testcase name="ValidateX1_DVRDCT_CSGResidential_2" classname="com.comcast.bulkOM.X1_DVRDCT">
    <skipped/>
  </testcase> <!-- ValidateX1_DVRDCT_CSGResidential_2 -->
</testsuite> <!-- com.comcast.bulkOM.X1_DVRDCT -->
